profiling: export profile_event symbols
* profile_event_register/unregister are KMI symbols now

>>>
ERROR: Differences between ksymtab and symbol list detected!
Symbols missing from ksymtab:
 - profile_event_register
 - profile_event_unregister
 <<<

Signed-off-by: chickendrop89 <chickendrop89@gmail.com>