lib: zstd: bring back missing symbols
* A fix for following warnings:
ERROR: Differences between ksymtab and symbol list detected!
Symbols missing from ksymtab:
 - ZSTD_CStreamWorkspaceBound
 - ZSTD_DStreamWorkspaceBound
 - ZSTD_compressStream
 - ZSTD_decompressStream
 - ZSTD_endStream
 - ZSTD_getParams
 - ZSTD_initCStream
 - ZSTD_initDStream
 - ZSTD_maxCLevel

 [Commit by ztc1997] https://github.com/ztc1997/android_gki_kernel_5.15_common/commit/78b9ae7534e790c283cafc6d2f07ddf4abccfb58

Signed-off-by: chickendrop89 <chickendrop89@gmail.com>